version: '3'

services:
  javaapp:
    image: saboora/bankweb:54
    ports:
      - 8090:8080
    volumes:
      - /$(pwd):/usr/local/tomcat/webapps
  mysqlapp:
    image: saboora/banksql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret 
    ports:
      - 3311:3306

networks: 
   driver: bridge
   name: banknet
